### ISSUE TITLE
[Feature] Show to Players

### ISSUE THREAD

**Issue by brunocalado** [Larkinabout/fvtt-challenge-tracker#1]
Thank you for this module. It's great.

Is it possible to add a button to share the current tracker view to the players? It's just to show then the current situation. They shouldn't be able to change it.

Tks.

**Comment by Larkinabout** [comment]
Hi @brunocalado, that feature is already in the latest release. When you execute the macro, it also opens a view-only version of the Challenge Tracker for all players. If they want, players can move the tracker around and minimise/maximise it, but they cannot otherwise interact with it to fill in segments or close the tracker.

**Comment by brunocalado** [comment]
tks
